# see https://dev.classmethod.jp/articles/eslint-configurations-2020/
# note that eslint-plugin-prettier is deprecated
env:
  es2020: true
  jest/globals: true
  browser: true
  jquery: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - jest
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
globals:
  dat: true
  THREE: true
  NodeJS: true
  editor: true
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  no-unreachable: error
  no-undef: error
